spring:
  config:
    import: application-secret.properties

  datasource:
    driver-class-name: org.h2.Driver
    url: ${TEST_DATABASE_URL}
    username: ${TEST_DATABASE_USERNAME}
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console