spring:
  web:
    resources:
      add-mappings: false

  config:
    import: application-secret.properties

  datasource:
    driver-class-name: org.h2.Driver
    url: ${LOCAL_DATABASE_URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console